POST http://localhost:3002/product/
content-type: application/json

{

}

###

GET http://localhost:3002/product/1

###

PATCH http://localhost:3002/product/1
content-type: application/json

{

}

###

DELETE http://localhost:3002/product/1

