POST http://localhost:3002/restaurant/
content-type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJmZWxpcEBnbWFpbC5jb20iLCJyZXN0YXVyYW50IjoxNywiaWF0IjoxNzE1MDk2NTUxLCJleHAiOjE3MTU3MDEzNTF9.q6fXXkNB8gBfCk8Gyob7L58PPkJomChYlHhXrXOOCaM
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

"Somoko"
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="picture"; filename="1.png"
Content-Type: image/png

< ./1.png
###

GET http://localhost:3002/restaurant/17

###

PATCH http://localhost:3002/restaurant/2
content-type: application/json

{
  "name": "jotinha"
}

###

DELETE http://localhost:3002/restaurant/2

