POST http://localhost:3002/user/
content-type: application/json

{
  "name": "felipe",
  "email": "felipe@gmail.com",
  "password": "senha1"
}

###

GET http://localhost:3002/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJmZWxpcGVAZ21haWwuY29tIiwicmVzdGF1cmFudCI6bnVsbCwiaWF0IjoxNzE1MDMxNjk5LCJleHAiOjE3MTU2MzY0OTl9.OONsPQzYQYUzQIDbYB_oDFV0Q-1D0h-W6EyYK6x2Co4

###

PATCH http://localhost:3002/user/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJmZWxpcEBnbWFpbC5jb20iLCJyZXN0YXVyYW50IjoxNywiaWF0IjoxNzE1MDMyMTM5LCJleHAiOjE3MTU2MzY5Mzl9.kep5gjyPB_OxHX9miVOjI1X6UZ9UbIzGqaA_pIpLbjo

{
  "name": "Felip",
  "email": "felip@gmail.com",
  "password": "senha1"
}

###

DELETE http://localhost:3002/user/

